import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/global/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const reaver = localFont({
  src: [
    { path: "./fonts/Reaver-Bold.woff", weight: "700" },
    {
      path: "./fonts/Reaver-SemiBold.woff",
      weight: "600",
    },
    {
      path: "./fonts/Reaver-Regular.woff",
      weight: "400",
    },
  ],
  variable: "--font-Reaver",
});

const radiance = localFont({
  src: [
    {
      path: "./fonts/radiance-semibold.woff",
      weight: "600",
    },
    {
      path: "./fonts/radiance.woff",
      weight: "400",
    },
  ],
  variable: "--font-Radiance",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${reaver.variable} ${radiance.variable}`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
